//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sitecore.DiagnosticsTool.WinApp.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sitecore.DiagnosticsTool.WinApp.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data is not available.
        /// </summary>
        public static string DataIsNotAvailable {
            get {
                return ResourceManager.GetString("DataIsNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diagnostics has been canceled by user.
        /// </summary>
        public static string DiagnosticsCanceled {
            get {
                return ResourceManager.GetString("DiagnosticsCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diagnostics completed.
        /// </summary>
        public static string DiagnosticsCompleted {
            get {
                return ResourceManager.GetString("DiagnosticsCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred during diagnostics.
        /// </summary>
        public static string DiagnosticsError {
            get {
                return ResourceManager.GetString("DiagnosticsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diagnostics has been interrupted.
        /// </summary>
        public static string DiagnosticsInterrupted {
            get {
                return ResourceManager.GetString("DiagnosticsInterrupted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running test {0} of {1}.
        /// </summary>
        public static string DiagnosticsRunning {
            get {
                return ResourceManager.GetString("DiagnosticsRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Images/Configuration.png.
        /// </summary>
        public static string Icon_Configuration {
            get {
                return ResourceManager.GetString("Icon_Configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Images/Diagnostics.png.
        /// </summary>
        public static string Icon_Diagnostics {
            get {
                return ResourceManager.GetString("Icon_Diagnostics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Images/Resources.png.
        /// </summary>
        public static string Icon_Resources {
            get {
                return ResourceManager.GetString("Icon_Resources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Images/Report.png.
        /// </summary>
        public static string Icon_Results {
            get {
                return ResourceManager.GetString("Icon_Results", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Images/Welcome.png.
        /// </summary>
        public static string Icon_Welcome {
            get {
                return ResourceManager.GetString("Icon_Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string MainWizardView_Button_Finish {
            get {
                return ResourceManager.GetString("MainWizardView_Button_Finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string MainWizardView_Button_MoveBack {
            get {
                return ResourceManager.GetString("MainWizardView_Button_MoveBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string MainWizardView_Button_MoveNext {
            get {
                return ResourceManager.GetString("MainWizardView_Button_MoveNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start over.
        /// </summary>
        public static string MainWizardView_Button_Restart {
            get {
                return ResourceManager.GetString("MainWizardView_Button_Restart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start over.
        /// </summary>
        public static string MainWizardView_Button_StartOver {
            get {
                return ResourceManager.GetString("MainWizardView_Button_StartOver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration.
        /// </summary>
        public static string PageDisplayName_Configuration {
            get {
                return ResourceManager.GetString("PageDisplayName_Configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diagnostics.
        /// </summary>
        public static string PageDisplayName_Diagnostics {
            get {
                return ResourceManager.GetString("PageDisplayName_Diagnostics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources.
        /// </summary>
        public static string PageDisplayName_Resources {
            get {
                return ResourceManager.GetString("PageDisplayName_Resources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results.
        /// </summary>
        public static string PageDisplayName_Results {
            get {
                return ResourceManager.GetString("PageDisplayName_Results", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        public static string PageDisplayName_Welcome {
            get {
                return ResourceManager.GetString("PageDisplayName_Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select tests to run by choosing appropriate categories:.
        /// </summary>
        public static string PageTitle_Configuration {
            get {
                return ResourceManager.GetString("PageTitle_Configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running diagnostics:.
        /// </summary>
        public static string PageTitle_Diagnostics {
            get {
                return ResourceManager.GetString("PageTitle_Diagnostics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add SSPG packages from the single Sitecore solution to analyze (or ZIP files with configs, logs and sitecore.version.xml):.
        /// </summary>
        public static string PageTitle_Resources {
            get {
                return ResourceManager.GetString("PageTitle_Resources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View the results here:.
        /// </summary>
        public static string PageTitle_Results {
            get {
                return ResourceManager.GetString("PageTitle_Results", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string PageTitle_Welcome {
            get {
                return ResourceManager.GetString("PageTitle_Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while generating the report.
        /// </summary>
        public static string ReportError {
            get {
                return ResourceManager.GetString("ReportError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Images/SitecoreLogo.png.
        /// </summary>
        public static string SitecoreLogo {
            get {
                return ResourceManager.GetString("SitecoreLogo", resourceCulture);
            }
        }
    }
}
